<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class TagController extends Controller
{
    /**
     * List all tags (admin).
     */
    public function index(): View
    {
        $tags = Tag::withCount('posts')
            ->latest()
            ->paginate(15);

        return view('dashboard.tags.index', compact('tags'));
    }

    /**
     * Store a newly created tag.
     * Slug is auto-generated by the model's booted() hook.
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255', 'unique:tags,name'],
        ]);

        Tag::create(['name' => $request->name]);

        return redirect()
            ->route('dashboard.tags.index')
            ->with('success', 'Tag created successfully.');
    }

    /**
     * Show the form for editing a tag (admin).
     */
    public function edit(Tag $tag): View
    {
        return view('dashboard.tags.edit', compact('tag'));
    }

    /**
     * Update the specified tag.
     */
    public function update(Request $request, Tag $tag): RedirectResponse
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255', 'unique:tags,name,' . $tag->id],
        ]);

        $tag->update(['name' => $request->name]);

        return redirect()
            ->route('dashboard.tags.index')
            ->with('success', 'Tag updated successfully.');
    }

    /**
     * Delete a tag — only if it has no associated posts.
     */
    public function destroy(Tag $tag): RedirectResponse
    {
        if ($tag->posts()->exists()) {
            return redirect()
                ->route('dashboard.tags.index')
                ->with('error', 'Cannot delete a tag that has posts associated with it.');
        }

        $tag->delete();

        return redirect()
            ->route('dashboard.tags.index')
            ->with('success', 'Tag deleted successfully.');
    }

    /**
     * Public-facing tag archive page.
     * Route: GET /tag/{slug}  →  name: tag.show
     */
    public function show(Tag $tag): View
    {
        $posts = $tag->posts()
            ->where('status', 'published')
            ->where('published_at', '<=', now())
            ->with(['author', 'category'])
            ->latest('published_at')
            ->paginate(12);

        return view('pages.news.tag', compact('tag', 'posts'));
    }
}